### ISSUE TITLE
SBT files inconsistencies/review

### ISSUE THREAD

**Issue by Zejnilovic** [AbsaOSS/fa-db#109]
## Background
I went over the sbt files, both master and PRs, and identified a few places we can improve on.

```[tasklist]
### Tasks
- [ ] Parent project is initialized but never used
- [ ] Double settings for each project. One setting "everything else", second setting JaCoCo. Merge them.
- [ ] Defining printScalaVersion for ThisBuild gets evaluated only once and works the same way as the out-of-the-box SBT info log. PrintScreen bellow. 
- [ ] SontaypeProfileName - move it to publish.sbt
```

_Output of the print scala version_ 
![Screenshot 2024-01-05 at 11 05 27](https://github.com/AbsaOSS/fa-db/assets/17467768/f0d4aeaf-9677-4e5e-8c16-4e397f45fdda)
